{
 "title": "pgSCV: Patroni (NEW)",
 "description": "Patroni dashboard for pgSCV metrics (Prometheus version, pgSCV v0.14.0 edition)",
 "tags": [ "pgSCV" ],
 "time": { "from": "now-3h", "to": "now-1m" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds", "label": "DS", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(pgscv_services_registered_total{service=\"patroni\"},instance)"
    }
   },
   {
    "name": "patroni",
    "label": "Patroni",
    "query": {
     "query": "label_values(pgscv_services_registered_total{instance=\"$instance\", service=\"patroni\"},service_id)"
    }
   },
   {
    "name": "scope",
    "label": "Scope",
    "query": {
     "query": "label_values(patroni_postgres_running{service_id=\"$patroni\"},scope)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Patroni overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "Current status of Patroni service.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_up{service_id=\"$patroni\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node name",
   "type": "stat",
   "description": "Patroni node name.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(patroni_node_name{instance=\"$instance\",service_id=\"$patroni\",scope=\"$scope\"}) by (node_name)"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "Patroni version.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(patroni_version{instance=\"$instance\",service_id=\"$patroni\",scope=\"$scope\"}) by (version)"
    }
   ]
  },
  {
   "title": "Node status",
   "type": "stat",
   "description": "Patroni node status (Leader or Follower).",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_master{instance=\"$instance\",service_id=\"$patroni\",scope=\"$scope\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster lock",
   "type": "stat",
   "description": "Patroni cluster lock status.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_cluster_unlocked{instance=\"$instance\",service_id=\"$patroni\",scope=\"$scope\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pause/Resume mode",
   "type": "stat",
   "description": "Patroni pause or resume mode for the cluster.\n\nSee docs https://patroni.readthedocs.io/en/master/pause.html for more info.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_is_paused{instance=\"$instance\",service_id=\"$patroni\",scope=\"$scope\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DCS last seen",
   "type": "stat",
   "description": "Epoch timestamp when DCS was last contacted successfully by Patroni.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_dcs_last_seen{instance=\"$instance\",service_id=\"$patroni\",scope=\"$scope\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest timeline switched",
   "type": "stat",
   "description": "Epoch seconds since latest timeline switched.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "now()-patroni_last_timeline_change_seconds{instance=\"$instance\",service_id=\"$patroni\",scope=\"$scope\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replica",
   "type": "stat",
   "description": "Is replica.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_replica{instance=\"$instance\",service_id=\"$patroni\",scope=\"$scope\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Standby leader",
   "type": "stat",
   "description": "Is standby leader.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_standby_leader{instance=\"$instance\",service_id=\"$patroni\",scope=\"$scope\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replay paused",
   "type": "stat",
   "description": "Is 1 if the replaying of Postgres transaction log is paused, 0 otherwise.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_xlog_paused{instance=\"$instance\",service_id=\"$patroni\",scope=\"$scope\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Patroni settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "DCS failsafe mode",
     "type": "stat",
     "description": "DCS Failsafe Mode.\n\nSee docs https://patroni.readthedocs.io/en/master/dcs_failsafe_mode.html for more info.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "patroni_failsafe_mode_is_active{instance=\"$instance\",service_id=\"$patroni\",scope=\"$scope\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Loop wait",
     "type": "stat",
     "description": "The number of seconds the loop will sleep.\n\nRule: loop_wait + 2 * retry_timeout <= ttl\n\nSee loop_wait settings in docs https://patroni.readthedocs.io/en/latest/dynamic_configuration.html for more info.",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "patroni_loop_wait{instance=\"$instance\",service_id=\"$patroni\",scope=\"$scope\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Retry timeout",
     "type": "stat",
     "description": "Timeout for DCS and PostgreSQL operation retries (in seconds).\n\nRule: loop_wait + 2 * retry_timeout <= ttl\n\nSee retry_timeout settings in docs https://patroni.readthedocs.io/en/latest/dynamic_configuration.html for more info.",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "patroni_retry_timeout{instance=\"$instance\",service_id=\"$patroni\",scope=\"$scope\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TTL",
     "type": "stat",
     "description": "The TTL to acquire the leader lock (in seconds).\n\nRule: loop_wait + 2 * retry_timeout <= ttl\n\nSee ttl settings in docs https://patroni.readthedocs.io/en/latest/dynamic_configuration.html for more info.",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "patroni_ttl{instance=\"$instance\",service_id=\"$patroni\",scope=\"$scope\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max lag on failover",
     "type": "stat",
     "description": "The maximum bytes a follower may lag to be able to participate in leader election.\n\nSee maximum_lag_on_failover settings in docs https://patroni.readthedocs.io/en/latest/dynamic_configuration.html",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "patroni_maximum_lag_on_failover{instance=\"$instance\",service_id=\"$patroni\",scope=\"$scope\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "PostgreSQL overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "PostgreSQL running",
     "type": "stat",
     "description": "Is 1 if Postgres is running, 0 otherwise.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "patroni_postgres_running{instance=\"$instance\",service_id=\"$patroni\",scope=\"$scope\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PostgreSQL uptime",
     "type": "stat",
     "description": "PostgreSQL uptime.",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "now()-patroni_postmaster_start_time{instance=\"$instance\",service_id=\"$patroni\",scope=\"$scope\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PostgreSQL pending restart",
     "type": "stat",
     "description": "Is 1 if the node needs a restart, 0 otherwise.",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "patroni_pending_restart{instance=\"$instance\",service_id=\"$patroni\",scope=\"$scope\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PostgreSQL timeline",
     "type": "stat",
     "description": "PostgreSQL timeline.",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "patroni_postgres_timeline{instance=\"$instance\",service_id=\"$patroni\",scope=\"$scope\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PostgreSQL version",
     "type": "stat",
     "description": "PostgreSQL version.",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "patroni_postgres_server_version{instance=\"$instance\",service_id=\"$patroni\",scope=\"$scope\"}"
      }
     ]
    },
    {
     "title": "PostgreSQL streaming",
     "type": "stat",
     "description": "Is 1 if Postgres is streaming, 0 otherwise.",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "patroni_postgres_streaming{instance=\"$instance\",service_id=\"$patroni\",scope=\"$scope\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PostgreSQL is archive recovery",
     "type": "stat",
     "description": "Is 1 if Postgres is replicating from archive, 0 otherwise.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "patroni_postgres_in_archive_recovery{instance=\"$instance\",service_id=\"$patroni\",scope=\"$scope\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PostgreSQL synchronous standby",
     "type": "stat",
     "description": "Is 1 if synchronous mode is active, 0 if inactive.\n\nSee docs https://patroni.readthedocs.io/en/latest/replication_modes.html#synchronous-mode for more info.",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "patroni_sync_standby{instance=\"$instance\",service_id=\"$patroni\",scope=\"$scope\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "PostgreSQL WAL info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Primary WAL location",
     "type": "timeseries",
     "description": "Current location of the Postgres transaction log, 0 if this node is a replica.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "patroni_xlog_location{instance=\"$instance\",scope=\"$scope\"}",
       "legendFormat": "{{service_id}}"
      }
     ]
    },
    {
     "title": "Replica received WAL location",
     "type": "timeseries",
     "description": "Current location of the received Postgres transaction log, 0 if this node is the leader.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "patroni_xlog_received_location{instance=\"$instance\",scope=\"$scope\"}",
       "legendFormat": "{{service_id}}"
      }
     ]
    },
    {
     "title": "Replica replayed WAL location",
     "type": "timeseries",
     "description": "Current location of the replayed Postgres transaction log, 0 if this node is the leader.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "patroni_xlog_replayed_location{instance=\"$instance\",scope=\"$scope\"}",
       "legendFormat": "{{service_id}}"
      }
     ]
    },
    {
     "title": "Replica replayed WAL timestamp",
     "type": "timeseries",
     "description": "Current timestamp of the replayed Postgres transaction log, 0 if null.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "now()-patroni_xlog_replayed_timestamp{instance=\"$instance\",scope=\"$scope\"}",
       "legendFormat": "{{service_id}}"
      }
     ]
    }
   ]
  }
 ]
}