{
 "title": "Pods",
 "description": "CPU/Memory/Network/ usage for pods and containers",
 "tags": [ "Pod" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "2m" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_memory_swap{job=~\"kubernetes-.*\", image!=\"\"}, namespace)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(container_memory_swap{job=~\"kubernetes-.*\", image!=\"\", namespace=~\"^($namespace)$\"}, instance)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_memory_swap{job=~\"kubernetes-.*\", image!=\"\", namespace=~\"^($namespace)$\",instance=~\"$node\"}, pod)"
    }
   },
   {
    "name": "podGroup",
    "query": {
     "query": "label_values(container_memory_swap{pod=~\"$pod\"},pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_memory_swap{job=~\"kubernetes-.*\", image!=\"\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\",container!=\"POD\"}, container)"
    }
   },
   {
    "name": "node_name",
    "query": {
     "query": "label_values(container_memory_swap{job=~\"kubernetes-.*\", image!=\"\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}, instance)"
    }
   },
   {
    "name": "node_type",
    "query": {
     "query": "label_values(node_boot_time_seconds{instance=~\"$node_name\"},nodetype)"
    }
   },
   {
    "name": "node_arch",
    "query": {
     "query": "label_values(node_boot_time_seconds{instance=~\"$node_name\"},kubernetes_io_arch)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Network I/O ($interval avg) | $node_name | $node_arch | $node_type",
   "type": "timeseries",
   "description": "Network activity at Pod level (eth0 network card)",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (interface) (rate (container_network_receive_bytes_total{namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[$interval]))",
     "legendFormat": "received {{interface}}"
    },
    {
     "expr": "- sum by (interface) (rate (container_network_transmit_bytes_total{ namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[$interval]))",
     "legendFormat": "sent {{interface}}"
    }
   ]
  },
  { "title": "$container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "container" },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "CPU usage at container level \n\nthrottled percentage := container_cpu_cfs_throttled_periods_total / container_cpu_cfs_periods_total on 5m period \n, i.e. the percentage of CPU periods where the container ran but was throttled (stopped from running the whole CPU period).\n\nVPR New Req is the Vertical Pod Recommender recommendation for the CPU Request (based on a 7 days measurement)\n\nDrill down to \"Pods Java\" Dashboard",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits_cpu_cores{pod=~\"^$pod$\",namespace=~\"^$namespace$\",container=~\"^($container)$\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"^$pod$\",namespace=~\"^$namespace$\",container=~\"^($container)$\"}[$interval]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "max(kube_pod_container_resource_requests_cpu_cores{pod=~\"^$pod$\",namespace=~\"^$namespace$\",container=~\"^($container)$\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_periods_total{pod=~\"^$pod$\",namespace=~\"^$namespace$\",container=~\"^($container)$\"}[5m]) / rate(container_cpu_cfs_periods_total{pod=~\"^$pod$\",namespace=~\"^$namespace$\",container=~\"^($container)$\"}[5m]) )",
     "legendFormat": "Throttling %"
    },
    {
     "expr": "max(vpr_recommendation_requests_cpu_cores{pod=~\"$podGroup.*\",container=\"$container\"})",
     "legendFormat": "VPR New Req"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Mem usage at container level (only meaningful for non-Java based containers).if close to 100% of limit OOMKiller is triggered by OCP.The working set memory usage is without the FS cache (that can be evicted under memory pressure).\n\nVPR New Req/Limit is the Vertical Pod Recommender recommendation for the Mem Request/Limit (based on a 7 days measurement)\n\nDrill down to \"Pods Java\" Dashboard",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits_memory_bytes{pod=~\"^$pod$\",namespace=~\"^$namespace$\",container=~\"^($container)$\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "max(container_memory_working_set_bytes{pod=~\"^$pod$\",namespace=~\"^$namespace$\",container=~\"^($container)$\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "max(kube_pod_container_resource_requests_memory_bytes{pod=~\"^$pod$\",namespace=~\"^$namespace$\",container=~\"^($container)$\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "max(vpr_recommendation_requests_memory_bytes{pod=~\"$podGroup.*\",container=\"$container\"})",
     "legendFormat": "VPR New Req"
    },
    {
     "expr": "max(vpr_recommendation_limits_memory_bytes{pod=~\"$podGroup.*\",container=\"$container\"})",
     "legendFormat": "VPR New Limit"
    }
   ]
  }
 ]
}