{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "CPU",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$deployment_namespace\",pod=~\"$deployment_name.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$deployment_namespace\",pod=~\"$deployment_name.*\"}) / 1024^3"
    }
   ]
  },
  {
   "title": "Network",
   "type": "singlestat",
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$deployment_namespace\",pod=~\"$deployment_name.*\"}[3m])) + sum(rate(container_network_receive_bytes_total{namespace=\"$deployment_namespace\",pod=~\"$deployment_name.*\"}[3m]))"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Desired Replicas",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_deployment_status_observed_generation{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_deployment_metadata_generation{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Replicas",
   "type": "graph",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "current replicas"
    },
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "available"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "unavailable"
    },
    {
     "expr": "min(kube_deployment_status_replicas_updated{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "updated"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "desired"
    }
   ]
  }
 ]
}
{
 "title": "New Row",
 "panels": [
  {
   "title": "Idle CPU",
   "type": "graph",
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu{mode=\"idle\"}[2m])) * 100"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "sum(node_load1)", "legendFormat": "load 1m" },
    { "expr": "sum(node_load5)", "legendFormat": "load 5m" },
    { "expr": "sum(node_load15)", "legendFormat": "load 15m" }
   ]
  }
 ]
}
{
 "title": "New Row",
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal) - sum(node_memory_MemFree) - sum(node_memory_Buffers) - sum(node_memory_Cached)",
     "legendFormat": "memory usage"
    },
    { "expr": "sum(node_memory_Buffers)", "legendFormat": "memory buffers" },
    { "expr": "sum(node_memory_Cached)", "legendFormat": "memory cached" },
    { "expr": "sum(node_memory_MemFree)", "legendFormat": "memory free" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((sum(node_memory_MemTotal) - sum(node_memory_MemFree) - sum(node_memory_Buffers) - sum(node_memory_Cached)) / sum(node_memory_MemTotal)) * 100"
    }
   ]
  }
 ]
}
{
 "title": "New Row",
 "panels": [
  {
   "title": "Disk I/O",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_bytes_read[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(node_disk_bytes_written[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(rate(node_disk_io_time_ms[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "singlestat",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size{device!=\"rootfs\"}) - sum(node_filesystem_free{device!=\"rootfs\"})) / sum(node_filesystem_size{device!=\"rootfs\"})"
    }
   ]
  }
 ]
}
{
 "title": "New Row",
 "panels": [
  {
   "title": "Network Received",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes{device!~\"lo\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes{device!~\"lo\"}[5m]))"
    }
   ]
  }
 ]
}
{
 "title": "New Row",
 "panels": [
  {
   "title": "Cluster Pod Utilization",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(kube_pod_info)", "legendFormat": "Current number of Pods" },
    {
     "expr": "sum(kube_node_status_capacity_pods)",
     "legendFormat": "Maximum capacity of pods"
    }
   ]
  },
  {
   "title": "Pod Utilization",
   "type": "singlestat",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (sum(kube_node_status_capacity_pods) - sum(kube_pod_info)) / sum(kube_node_status_capacity_pods) * 100"
    }
   ]
  }
 ]
}
{
 "title": "Row",
 "panels": [
  {
   "title": "Control Plane Components Down",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{job=~\"apiserver|kube-scheduler|kube-controller-manager\"} == 0)"
    }
   ]
  },
  {
   "title": "Alerts Firing",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  },
  {
   "title": "Alerts Pending",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"pending\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  },
  {
   "title": "Crashlooping Pods",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(increase(kube_pod_container_status_restarts[1h]) > 5)"
    }
   ]
  }
 ]
}
{
 "title": "Row",
 "panels": [
  {
   "title": "Node Not Ready",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\"})"
    }
   ]
  },
  {
   "title": "Node Disk Pressure",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Node Memory Pressure",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Unschedulable",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)"
    }
   ]
  }
 ]
}
{
 "title": "Cluster Health",
 "panels": [
  {
   "title": "Control Plane UP",
   "type": "singlestat",
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(up{job=~\"apiserver|kube-scheduler|kube-controller-manager\"} == 0)"
    }
   ]
  },
  {
   "title": "Alerts Firing",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  }
 ]
}
{
 "title": "Control Plane Status",
 "panels": [
  {
   "title": "API Servers UP",
   "type": "singlestat",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(up{job=\"apiserver\"} == 1) / count(up{job=\"apiserver\"})) * 100"
    }
   ]
  },
  {
   "title": "Controller Managers UP",
   "type": "singlestat",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-controller-manager\"} == 1) / count(up{job=\"kube-controller-manager\"})) * 100"
    }
   ]
  },
  {
   "title": "Schedulers UP",
   "type": "singlestat",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-scheduler\"} == 1) / count(up{job=\"kube-scheduler\"})) * 100"
    }
   ]
  },
  {
   "title": "Crashlooping Control Plane Pods",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(increase(kube_pod_container_status_restarts{namespace=~\"kube-system|tectonic-system\"}[1h]) > 5)"
    }
   ]
  }
 ]
}
{
 "title": "Capacity Planning",
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "singlestat",
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(100 - (avg by (instance) (rate(node_cpu{job=\"node-exporter\",mode=\"idle\"}[5m])) * 100)) / count(node_cpu{job=\"node-exporter\",mode=\"idle\"})"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "singlestat",
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((sum(node_memory_MemTotal) - sum(node_memory_MemFree) - sum(node_memory_Buffers) - sum(node_memory_Cached)) / sum(node_memory_MemTotal)) * 100"
    }
   ]
  },
  {
   "title": "Filesystem Utilization",
   "type": "singlestat",
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size{device!=\"rootfs\"}) - sum(node_filesystem_free{device!=\"rootfs\"})) / sum(node_filesystem_size{device!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Pod Utilization",
   "type": "singlestat",
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (sum(kube_node_status_capacity_pods) - sum(kube_pod_info)) / sum(kube_node_status_capacity_pods) * 100"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "API Servers UP",
   "type": "singlestat",
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"apiserver\"} == 1) / sum(up{job=\"apiserver\"})) * 100"
    }
   ]
  },
  {
   "title": "Controller Managers UP",
   "type": "singlestat",
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-controller-manager\"} == 1) / sum(up{job=\"kube-controller-manager\"})) * 100"
    }
   ]
  },
  {
   "title": "Schedulers UP",
   "type": "singlestat",
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-scheduler\"} == 1) / sum(up{job=\"kube-scheduler\"})) * 100"
    }
   ]
  },
  {
   "title": "API Server Request Error Rate",
   "type": "singlestat",
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum by(instance) (rate(apiserver_request_count{code=~\"5..\"}[5m])) / sum by(instance) (rate(apiserver_request_count[5m]))) * 100"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "API Server Request Latency",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(verb) (rate(apiserver_latency_seconds:quantile[5m]) >= 0)"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "End to End Scheduling Latency",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cluster:scheduler_e2e_scheduling_latency_seconds:quantile"
    }
   ]
  },
  {
   "title": "API Server Request Rates",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (rate(apiserver_request_count{code!~\"2..\"}[5m]))",
     "legendFormat": "Error Rate"
    },
    {
     "expr": "sum by(instance) (rate(apiserver_request_count[5m]))",
     "legendFormat": "Request Rate"
    }
   ]
  }
 ]
}
{
 "title": "CPU Cores",
 "panels": [
  {
   "title": "CPU Cores",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_cpu_cores) by (instance))",
     "legendFormat": "Allocatable CPU Cores"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance))",
     "legendFormat": "Requested CPU Cores"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance)) / min(sum(kube_node_status_allocatable_cpu_cores) by (instance)) * 100"
    }
   ]
  }
 ]
}
{
 "title": "Memory",
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_memory_bytes) by (instance))",
     "legendFormat": "Allocatable Memory"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance))",
     "legendFormat": "Requested Memory"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance)) / min(sum(kube_node_status_allocatable_memory_bytes) by (instance)) * 100"
    }
   ]
  }
 ]
}
{
 "title": "New Row",
 "panels": [
  {
   "title": "Idle CPU",
   "type": "graph",
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu{mode=\"idle\", instance=\"$server\"}[5m])) * 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"$server\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{instance=\"$server\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{instance=\"$server\"}",
     "legendFormat": "load 15m"
    }
   ]
  }
 ]
}
{
 "title": "New Row",
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=\"$server\"} - node_memory_MemFree{instance=\"$server\"} - node_memory_Buffers{instance=\"$server\"} - node_memory_Cached{instance=\"$server\"}",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers{instance=\"$server\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached{instance=\"$server\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree{instance=\"$server\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((node_memory_MemTotal{instance=\"$server\"} - node_memory_MemFree{instance=\"$server\"}  - node_memory_Buffers{instance=\"$server\"} - node_memory_Cached{instance=\"$server\"}) / node_memory_MemTotal{instance=\"$server\"}) * 100"
    }
   ]
  }
 ]
}
{
 "title": "New Row",
 "panels": [
  {
   "title": "Disk I/O",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_read{instance=\"$server\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_written{instance=\"$server\"}[2m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_io_time_ms{instance=\"$server\"}[2m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "singlestat",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size{device!=\"rootfs\",instance=\"$server\"}) - sum(node_filesystem_free{device!=\"rootfs\",instance=\"$server\"})) / sum(node_filesystem_size{device!=\"rootfs\",instance=\"$server\"})"
    }
   ]
  }
 ]
}
{
 "title": "New Row",
 "panels": [
  {
   "title": "Network Received",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes{instance=\"$server\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes{instance=\"$server\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}
{
 "title": "Row",
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(container) (container_memory_usage_bytes{pod=\"$pod\", container=~\"$container\", container!=\"POD\", container!=\"\"})",
     "legendFormat": "Current: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{pod=\"$pod\", container=~\"$container\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{pod=\"$pod\", container=~\"$container\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  }
 ]
}
{
 "title": "Row",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container)(rate(container_cpu_usage_seconds_total{image!=\"\",container!=\"POD\", container!=\"\",pod=\"$pod\"}[1m]))",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{pod=\"$pod\", container=~\"$container\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{pod=\"$pod\", container=~\"$container\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  }
 ]
}
{
 "title": "New Row",
 "panels": [
  {
   "title": "Network I/O",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod) (rate(container_network_receive_bytes_total{pod=\"$pod\"}[1m])))",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "CPU",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$statefulset_namespace\",pod=~\"$statefulset_name.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$statefulset_namespace\",pod=~\"$statefulset_name.*\"}) / 1024^3"
    }
   ]
  },
  {
   "title": "Network",
   "type": "singlestat",
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$statefulset_namespace\",pod=~\"$statefulset_name.*\"}[3m])) + sum(rate(container_network_receive_bytes_total{namespace=\"$statefulset_namespace\",pod=~\"$statefulset_name.*\"}[3m]))"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Desired Replicas",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_statefulset_replicas{statefulset=\"$statefulset_name\",namespace=\"$statefulset_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(kube_statefulset_status_replicas{statefulset=\"$statefulset_name\",namespace=\"$statefulset_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_statefulset_status_observed_generation{statefulset=\"$statefulset_name\",namespace=\"$statefulset_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_statefulset_metadata_generation{statefulset=\"$statefulset_name\",namespace=\"$statefulset_namespace\"}) without (instance, pod)"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Replicas",
   "type": "graph",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "min(kube_statefulset_status_replicas{statefulset=\"$statefulset_name\",namespace=\"$statefulset_namespace\"}) without (instance, pod)",
     "legendFormat": "available"
    },
    {
     "expr": "max(kube_statefulset_replicas{statefulset=\"$statefulset_name\",namespace=\"$statefulset_namespace\"}) without (instance, pod)",
     "legendFormat": "desired"
    }
   ]
  }
 ]
}
{
 "title": "Knative Serving - Control Plane Efficiency",
 "description": "Knative Serving - Control Plane Efficiency",
 "tags": [ "Knative" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Namespace CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"knative-serving\"}[1m]))",
     "legendFormat": "knative-serving"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\"}[1m]))",
     "legendFormat": "default"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"monitoring\"}[1m]))",
     "legendFormat": "monitoring"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"argocd\"}[1m]))",
     "legendFormat": "argocd"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"istio-system\"}[1m]))",
     "legendFormat": "istio-system"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"kube-system\"}[1m]))",
     "legendFormat": "kube-system"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"kube-public\"}[1m]))",
     "legendFormat": "kube-public"
    }
   ]
  },
  {
   "title": "Namespace Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"knative-serving\"}[1m]))",
     "legendFormat": "knative-serving"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"monitoring\"}[1m]))",
     "legendFormat": "monitoring"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\"}[1m]))",
     "legendFormat": "default"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"argocd\"}[1m]))",
     "legendFormat": "argocd"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"istio-system\"}[1m]))",
     "legendFormat": "istio-system"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"kube-system\"}[1m]))",
     "legendFormat": "kube-system"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"kube-public\"}[1m]))",
     "legendFormat": "kube-public"
    }
   ]
  },
  {
   "title": "Control Plane vs Data Plane CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace!~\"knative-serving|monitoring|default|argocd|istio-system|kube-system|kube-public|^$\"}[1m]))",
     "legendFormat": "Data plane"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"knative-serving|monitoring|default|argocd|istio-system|kube-system|kube-public\"}[1m]))",
     "legendFormat": "Control plane"
    }
   ]
  },
  {
   "title": "Control Plane vs Data Plane Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace!~\"knative-serving|monitoring|default|argocd|istio-system|istio-system|kube-public|^$\"})",
     "legendFormat": "Data plane"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"knative-serving|monitoring|default|argocd|istio-system|istio-system|kube-public\"})",
     "legendFormat": "Control plane"
    }
   ]
  }
 ]
}
{
 "title": "Knative - Reconciler",
 "description": "Knative - Reconciler",
 "tags": [ "Knative" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "reconciler",
    "label": "Reconciler",
    "query": "label_values(controller_reconcile_count, reconciler)"
   },
   {
    "name": "key",
    "label": "Key",
    "query": "label_values(controller_reconcile_count{reconciler=\"$reconciler\"}, key)"
   }
  ]
 },
 "panels": [
  { "title": "Aggregate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reconcile Count (per min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (reconciler)(60 * rate(controller_reconcile_count[1m]))",
     "legendFormat": "{{reconciler}}"
    }
   ]
  },
  { "title": "Per Reconciler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "$reconciler Reconcile Count (per min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(60 * rate(controller_reconcile_count{reconciler=\"$reconciler\"}[1m]))",
     "legendFormat": "{{reconciler}}"
    }
   ]
  },
  {
   "title": "$reconciler Reconcile Latency Percentiles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(controller_reconcile_latency_bucket{reconciler=\"$reconciler\"}[1m])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(controller_reconcile_latency_bucket{reconciler=\"$reconciler\"}[1m])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(controller_reconcile_latency_bucket{reconciler=\"$reconciler\"}[1m])) by (le))",
     "legendFormat": "50th"
    }
   ]
  },
  { "title": "Per Reconciler & Key", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "$reconciler/$key Reconcile Count (per min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(60 * rate(controller_reconcile_count{reconciler=\"$reconciler\", key=\"$key\"}[1m]))",
     "legendFormat": "{{reconciler}}"
    }
   ]
  },
  {
   "title": "$reconciler/$key Reconcile Latency Percentiles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(controller_reconcile_latency_bucket{reconciler=\"$reconciler\", key=\"$key\"}[1m])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(controller_reconcile_latency_bucket{reconciler=\"$reconciler\", key=\"$key\"}[1m])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(controller_reconcile_latency_bucket{reconciler=\"$reconciler\", key=\"$key\"}[1m])) by (le))",
     "legendFormat": "50th"
    }
   ]
  }
 ]
}
{
 "title": "Knative Serving - Scaling Debugging",
 "description": "Knative Serving - Scaling Debugging",
 "tags": [ "Knative" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(autoscaler_desired_pods, namespace_name)"
   },
   {
    "name": "configuration",
    "label": "Configuration",
    "query": "label_values(autoscaler_desired_pods{namespace_name=\"$namespace\"}, configuration_name)"
   },
   {
    "name": "revision",
    "label": "Revision",
    "query": "label_values(autoscaler_desired_pods{namespace_name=\"$namespace\", configuration_name=\"$configuration\"}, revision_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Revision Pod Counts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Revision Pod Counts",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(autoscaler_actual_pods{namespace_name=\"$namespace\", configuration_name=\"$configuration\", revision_name=\"$revision\"})",
       "legendFormat": "Actual Pods"
      },
      {
       "expr": "sum(autoscaler_requested_pods{namespace_name=\"$namespace\", configuration_name=\"$configuration\", revision_name=\"$revision\"})",
       "legendFormat": "Requested Pods"
      },
      {
       "expr": "sum(autoscaler_pending_pods{namespace_name=\"$namespace\", configuration_name=\"$configuration\", revision_name=\"$revision\"})",
       "legendFormat": "Pending Pods"
      },
      {
       "expr": "sum(autoscaler_not_ready_pods{namespace_name=\"$namespace\", configuration_name=\"$configuration\", revision_name=\"$revision\"})",
       "legendFormat": "NotReady Pods"
      },
      {
       "expr": "sum(autoscaler_terminating_pods{namespace_name=\"$namespace\", configuration_name=\"$configuration\", revision_name=\"$revision\"})",
       "legendFormat": "Terminating Pods"
      }
     ]
    },
    {
     "title": "Request Concurrency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(activator_request_concurrency{namespace_name=\"$namespace\", configuration_name=\"$configuration\", revision_name=\"$revision\"})",
       "legendFormat": "Request Concurrency"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Usages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Revision CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=~\"$revision-deployment-.*\"})",
       "legendFormat": "Cores requested"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$revision-deployment-.*\", container=\"\"}[1m]))",
       "legendFormat": "Cores used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=~\"$revision-deployment-.*\"})",
       "legendFormat": "Core limit"
      }
     ]
    },
    {
     "title": "Pod Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=~\"$revision-deployment-.*\"})",
       "legendFormat": "Memory requested"
      },
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"$revision-deployment-.*\"})",
       "legendFormat": "Memory used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=~\"$revision-deployment-.*\"})"
      }
     ]
    }
   ]
  },
  { "title": "Autoscaler Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Pod Counts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(autoscaler_desired_pods{namespace_name=\"$namespace\", configuration_name=\"$configuration\", revision_name=\"$revision\"}) ",
     "legendFormat": "Desired Pods"
    },
    {
     "expr": "sum(autoscaler_observed_pods{namespace_name=\"$namespace\", configuration_name=\"$configuration\", revision_name=\"$revision\"})",
     "legendFormat": "Observed Pods"
    }
   ]
  },
  {
   "title": "Observed Concurrency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(autoscaler_stable_request_concurrency{namespace_name=\"$namespace\", configuration_name=\"$configuration\", revision_name=\"$revision\"})",
     "legendFormat": "Average Concurrency"
    },
    {
     "expr": "sum(autoscaler_panic_request_concurrency{namespace_name=\"$namespace\", configuration_name=\"$configuration\", revision_name=\"$revision\"})",
     "legendFormat": "Average Panic Concurrency"
    },
    {
     "expr": "sum(autoscaler_target_concurrency_per_pod{namespace_name=\"$namespace\", configuration_name=\"$configuration\", revision_name=\"$revision\"})",
     "legendFormat": "Target Concurrency"
    },
    {
     "expr": "sum(autoscaler_excess_burst_capacity{namespace_name=\"$namespace\", configuration_name=\"$configuration\", revision_name=\"$revision\"})",
     "legendFormat": "Excess Burst Capacity"
    }
   ]
  },
  {
   "title": "Observed RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(autoscaler_stable_requests_per_second{namespace_name=\"$namespace\", configuration_name=\"$configuration\", revision_name=\"$revision\"})",
     "legendFormat": "Average RPS"
    },
    {
     "expr": "sum(autoscaler_panic_requests_per_second{namespace_name=\"$namespace\", configuration_name=\"$configuration\", revision_name=\"$revision\"})",
     "legendFormat": "Average Panic RPS"
    },
    {
     "expr": "sum(autoscaler_target_requests_per_second{namespace_name=\"$namespace\", configuration_name=\"$configuration\", revision_name=\"$revision\"})",
     "legendFormat": "Target RPS"
    }
   ]
  },
  {
   "title": "Scrape time by revision",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.50, sum(rate(autoscaler_scrape_time_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "{{ revision_name }} (p50)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.90, sum(rate(autoscaler_scrape_time_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "{{ revision_name }} (p90)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.95, sum(rate(autoscaler_scrape_time_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "{{ revision_name }} (p95)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.99, sum(rate(autoscaler_scrape_time_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "{{ revision_name }} (p99)"
    }
   ]
  },
  {
   "title": "Panic Mode",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(autoscaler_panic_mode{namespace_name=\"$namespace\", configuration_name=\"$configuration\", revision_name=\"$revision\"} )",
     "legendFormat": "Panic Mode"
    }
   ]
  },
  { "title": "Activator Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Request Count in last minute by Response Code",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "round(sum(increase(activator_request_count{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\"}[1m])) by (response_code))",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  {
   "title": "Response Time in last minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.50, sum(rate(activator_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "{{ revision_name }} (p50)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.90, sum(rate(activator_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "{{ revision_name }} (p90)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.95, sum(rate(activator_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "{{ revision_name }} (p95)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.99, sum(rate(activator_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "{{ revision_name }} (p99)"
    }
   ]
  },
  {
   "title": "Request Concurrency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(activator_request_concurrency{namespace_name=\"$namespace\", configuration_name=\"$configuration\", revision_name=\"$revision\"})",
     "legendFormat": "Request Concurrency"
    }
   ]
  }
 ]
}
{
 "title": "Knative Serving - Revision HTTP Requests",
 "description": "Knative Serving - Revision HTTP Requests",
 "tags": [ "Knative" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(revision_request_count{namespace_name!=\"unknown\"}, namespace_name)"
   },
   {
    "name": "configuration",
    "label": "Configuration",
    "query": "label_values(revision_request_count{namespace_name=\"$namespace\", configuration_name!=\"unknown\"}, configuration_name)"
   },
   {
    "name": "revision",
    "label": "Revision",
    "query": "label_values(revision_request_count{namespace_name=\"$namespace\", configuration_name=~\"$configuration\", revision_name!=\"unknown\"}, revision_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview (average over the selected time range)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Request Volume",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(sum(rate(revision_request_count{namespace_name=\"$namespace\", revision_name=~\"$revision\", configuration_name=~\"$configuration\"}[1m])), 0.001)"
    }
   ]
  },
  {
   "title": "Success Rate (non-5xx responses)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(revision_request_count{response_code_class!=\"5xx\", namespace_name=\"$namespace\", revision_name=~\"$revision\", configuration_name=~\"$configuration\"}[1m])) / sum(rate(revision_request_count{namespace_name=\"$namespace\", revision_name=~\"$revision\", configuration_name=~\"$configuration\"}[1m]))"
    }
   ]
  },
  {
   "title": "4xx",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(revision_request_count{response_code_class=\"4xx\", namespace_name=\"$namespace\", revision_name=~\"$revision\", configuration_name=~\"$configuration\"}[1m])) "
    }
   ]
  },
  {
   "title": "5xx",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(revision_request_count{response_code_class=\"5xx\", namespace_name=\"$namespace\", revision_name=~\"$revision\", configuration_name=~\"$configuration\"}[1m])) "
    }
   ]
  },
  { "title": "Request Volume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Request Volume by Revision",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "label_replace(round(sum(rate(revision_request_count{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\"}[1m])) by (revision_name), 0.001), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "{{revision_name}}"
    }
   ]
  },
  {
   "title": "Request Volume by Response Code Class",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(revision_request_count{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\"}[1m])) by (response_code_class), 0.001)",
     "legendFormat": "{{ response_code_class }}"
    }
   ]
  },
  { "title": "Response Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Response Time by Revision",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.50, sum(rate(revision_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "{{ revision_name }} (p50)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.90, sum(rate(revision_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "{{ revision_name }} (p90)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.95, sum(rate(revision_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "{{ revision_name }} (p95)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.99, sum(rate(revision_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "{{ revision_name }} (p99)"
    }
   ]
  },
  {
   "title": "Response Time by Response Code Class",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.50, sum(rate(revision_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\",response_code_class=\"2xx\"}[1m])) by (le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "2xx (p50)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.50, sum(rate(revision_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\",response_code_class=\"3xx\"}[1m])) by (le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "3xx (p50)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.50, sum(rate(revision_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\",response_code_class=\"4xx\"}[1m])) by (le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "4xx (p50)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.50, sum(rate(revision_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\",response_code_class=\"5xx\"}[1m])) by (le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "5xx (p50)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.95, sum(rate(revision_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\",response_code_class=\"2xx\"}[1m])) by (le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "2xx (p95)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.95, sum(rate(revision_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\",response_code_class=\"3xx\"}[1m])) by (le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "3xx (p95)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.95, sum(rate(revision_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\",response_code_class=\"4xx\"}[1m])) by (le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "4xx (p95)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.95, sum(rate(revision_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\",response_code_class=\"5xx\"}[1m])) by (le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "5xx (p95)"
    }
   ]
  }
 ]
}
{
 "title": "Knative Serving - Revision CPU and Memory Usage",
 "description": "Knative Serving - Revision CPU and Memory Usage",
 "tags": [ "Knative" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_labels{label_serving_knative_dev_configuration=~\".+\"}, namespace)"
   },
   {
    "name": "configuration",
    "label": "Configuration",
    "query": "label_values(kube_pod_labels{label_serving_knative_dev_configuration=~\".+\", namespace=\"$namespace\"}, label_serving_knative_dev_configuration)"
   },
   {
    "name": "revision",
    "label": "Revision",
    "query": "label_values(kube_pod_labels{label_serving_knative_dev_configuration=~\".+\", namespace=\"$namespace\", label_serving_knative_dev_configuration=\"$configuration\"}, label_serving_knative_dev_revision)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$revision.*\", container != \"POD\", container != \"\"}[1m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"$revision.*\", container != \"POD\", container != \"\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}