apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      scrape_timeout: 10s
      keep_dropped_targets: 100
      sample_limit: 5000
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
            labels:
              tier: 'prometheus'

      - job_name: 'cadvisor'
        static_configs:
          - targets: ['cadvisor.observability.svc:8080']
            labels:
              name: 'cadvisor'

      - job_name: 'kubernetes-nodes'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
        - role: node
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics

      - job_name: "kubernetes-cadvisor"
        scrape_interval: 15s
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor

      - job_name: 'kubernetes-services'
        kubernetes_sd_configs:
        - role: service
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels: [__meta_kubernetes_service_name]
          target_label: service
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
          target_label: prometheus_io_scrape
          action: replace
        - source_labels: [__meta_kubernetes_service_port_name]
          regex: .*
          action: keep

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_pod_ip]
          regex: ''
          action: drop
        - source_labels: [__meta_kubernetes_pod_ip, __meta_kubernetes_pod_container_port_number]
          action: replace
          regex: (.+);(.+)
          replacement: ${1}:${2}
          target_label: __address__
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          target_label: prometheus_io_scrape
          action: replace
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          target_label: prometheus_io_path
          action: replace

      - job_name: 'etcd'
        scheme: https
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ['kube-system']
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_name]
            regex: etcd-minikube
            action: keep
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: __metrics_path__
            regex: (.+)
            replacement: /api/v1/namespaces/kube-system/pods/${1}:2379/proxy/metrics
          - target_label: __address__
            replacement: kubernetes.default.svc:443

      - job_name: 'kube-proxy'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__meta_kubernetes_node_name]
            target_label: __address__
            regex: (.+)
            replacement: ${1}:10249
          - target_label: __metrics_path__
            replacement: /metrics
              
      - job_name: 'kube-dns'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names: ['kube-system']
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            regex: kube-dns;metrics
            action: keep

      - job_name: 'kube-apiserver'
        scheme: https
        metrics_path: /metrics
        static_configs:
          - targets:
              - localhost:6443
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true

      # - job_name: 'kube-apiserver'
      #   scheme: https
      #   bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      #   tls_config:
      #     ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      #     insecure_skip_verify: true
      #   kubernetes_sd_configs:
      #   - role: pod
      #     namespaces:
      #       names: ['kube-system']
      #   relabel_configs:
      #   - source_labels: [__meta_kubernetes_pod_name]
      #     regex: kube-apiserver-.+
      #     action: keep
      #   - source_labels: [__meta_kubernetes_pod_name]
      #     target_label: __metrics_path__
      #     regex: (.+)
      #     replacement: /metrics  # kube-apiserver exposes metrics directly on 6443
      #   - source_labels: [__meta_kubernetes_pod_ip]
      #     target_label: __address__
      #     regex: (.+)
      #     replacement: ${1}:6443

      # - job_name: 'kube-controller-manager'
      #   kubernetes_sd_configs:
      #     - role: pod
      #       namespaces:
      #         names: ['kube-system']
      #   relabel_configs:
      #     # Only keep controller-manager pod
      #     - source_labels: [__meta_kubernetes_pod_name]
      #       regex: kube-controller-manager-.+
      #       action: keep
      #     # Set __address__ to pod IP + metrics port
      #     - source_labels: [__meta_kubernetes_pod_ip]
      #       target_label: __address__
      #       regex: (.+)
      #       replacement: ${1}:10252
      #     - target_label: __metrics_path__
      #       replacement: /metrics

      - job_name: 'kubernetes-endpoints'

      # - job_name: prometheus-second
      #   kubernetes_sd_configs:
      #   - role: endpoints
      #   relabel_configs:
      #   - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_label_app, __meta_kubernetes_endpoint_port_name]
      #     action: keep
      #     regex: observability;prometheus;web
      #   - source_labels: [__meta_kubernetes_namespace]
      #     target_label: namespace
      #   - source_labels: [__meta_kubernetes_pod_name]
      #     target_label: pod
      #   - source_labels: [__meta_kubernetes_service_name]
      #     target_label: service

      # - job_name: "kubernetes-apiservers"
      #   kubernetes_sd_configs:
      #     - role: endpoints
      #   scheme: https
      #   bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      #   tls_config:
      #     ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      #     insecure_skip_verify: false
      #   # authorization:
      #   #   credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      #   relabel_configs:
      #     - source_labels:
      #         [
      #           __meta_kubernetes_namespace,
      #           __meta_kubernetes_service_name,
      #           __meta_kubernetes_service_label_component,
      #           __meta_kubernetes_service_label_provider,
      #           __meta_kubernetes_endpoint_port_name,
      #         ]
      #       action: keep
      #       regex: default;apiserver;kubernetes;https

      # - job_name: kube-controller-manager
      #   kubernetes_sd_configs:
      #   - role: endpoints
      #   relabel_configs:
      #   - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_label_app, __meta_kubernetes_endpoint_port_name]
      #     action: keep
      #     regex: knative-monitoring;kube-controller-manager;http-metrics
      #   - source_labels: [__meta_kubernetes_namespace]
      #     target_label: namespace
      #   - source_labels: [__meta_kubernetes_pod_name]
      #     target_label: pod
      #   - source_labels: [__meta_kubernetes_service_name]
      #     target_label: service

      # - job_name: kube-scheduler
      #   kubernetes_sd_configs:
      #   - role: endpoints
      #   relabel_configs:
      #   - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_label_k8s_app, __meta_kubernetes_endpoint_port_name]
      #     action: keep
      #     regex: kube-system;kube-scheduler;http-metrics
      #   - source_labels: [__meta_kubernetes_namespace]
      #     target_label: namespace
      #   - source_labels: [__meta_kubernetes_pod_name]
      #     target_label: pod
      #   - source_labels: [__meta_kubernetes_service_name]
      #     target_label: service

      # - job_name: "kubernetes-nodes"
      #   scheme: https
      #   tls_config:
      #     ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      #   bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      #   kubernetes_sd_configs:
      #     - role: node
      #   relabel_configs:
      #   - action: labelmap
      #     regex: __meta_kubernetes_node_label_(.+)
      #   - target_label: __address__
      #     replacement: kubernetes.default.svc:443
      #   - source_labels: [__meta_kubernetes_node_name]
      #     target_label: __metrics_path__
      #     replacement: /api/v1/nodes/${1}/proxy/metrics

      # - job_name: kubernetes-cadvisor-second
      #   scrape_interval: 15s
      #   scheme: https
      #   tls_config:
      #     ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      #   bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      #   kubernetes_sd_configs:
      #   - role: node
      #   relabel_configs:
      #   - action: labelmap
      #     regex: __meta_kubernetes_node_label_(.+)
      #   - target_label: __address__
      #     replacement: kubernetes.default.svc:443
      #   - source_labels: [__meta_kubernetes_node_name]
      #     target_label: __metrics_path__
      #     replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor

      # - job_name: "kubernetes-service-endpoints"
      #   kubernetes_sd_configs:
      #   - role: endpoints
      #   relabel_configs:
      #   - action: labelmap
      #     regex: __meta_kubernetes_service_label_(.+)
      #   - source_labels: [__meta_kubernetes_namespace]
      #     action: replace
      #     target_label: namespace
      #   - source_labels: [__meta_kubernetes_service_name]
      #     action: replace
      #     target_label: service

      # - job_name: "kubernetes-services"
      #   metrics_path: /probe
      #   params:
      #     module: [http_2xx]
      #   kubernetes_sd_configs:
      #   - role: service
      #   relabel_configs:
      #   - source_labels: [__address__]
      #     target_label: __param_target
      #   - source_labels: [__param_target]
      #     target_label: instance
      #   - action: labelmap
      #     regex: __meta_kubernetes_service_label_(.+)
      #   - source_labels: [__meta_kubernetes_namespace]
      #     target_label: namespace
      #   - source_labels: [__meta_kubernetes_service_name]
      #     target_label: service

      # - job_name: "kubernetes-pods"
      #   kubernetes_sd_configs:
      #   - role: pod
      #   relabel_configs:
      #   - action: labelmap
      #     regex: __meta_kubernetes_pod_label_(.+)
      #   - source_labels: [__meta_kubernetes_namespace]
      #     action: replace
      #     target_label: namespace
      #   - source_labels: [__meta_kubernetes_pod_name]
      #     action: replace
      #     target_label: pod

    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alertmanager.observability.svc.cluster.local:9093
    rule_files:
    - "alert-rules.yml"
  alert-rules.yml: |
    groups:
    - name: WeekendAlerts
      rules:
        - alert: WeekendAlert
          expr: |
            (day_of_week() < 6) and (up == 0)
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Service down on a weekday"
            description: "The 'up' metric is 0, meaning a target is down, but only triggers on weekdays (Mon–Fri)."
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: prometheus
  template:
    metadata:
      labels:
        tier: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
          - --config.file=/etc/prometheus/prometheus.yml
          - --storage.tsdb.path=/prometheus
          - --storage.tsdb.retention.time=2d
          - --storage.tsdb.no-lockfile
          - --web.enable-lifecycle
          - --web.route-prefix=/
          ports:
          - containerPort: 9090
          resources:
            limits:
              memory: 2000Mi
          volumeMounts:
          - name: config-volume
            mountPath: /etc/prometheus
          - name: prometheus-storage
            mountPath: /prometheus
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-server-conf
          defaultMode: 420
      - name: prometheus-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: observability
spec:
  type: NodePort
  selector:
    tier: prometheus
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
      nodePort: 30090