apiVersion: v1
kind: Pod
metadata:
  name: centos-image-docker
spec:
  containers:
  - name: pod-case-0
    image: docker.io/centos/tools:latest
    command:
    - /sbin/init
---
apiVersion: v1
kind: Pod
metadata:
  name: centos-image-gcrio
spec:
  containers:
  - name: pod-case-0
    image: gcr.io/gcp-runtimes/centos7
    command:
    - /sbin/init
---
apiVersion: v1
kind: Pod
metadata:
  name: centos-image-quayio
spec:
  containers:
  - name: pod-case-0
    image: quay.io/centos/centos:centos7
    command:
    - /sbin/init
---
apiVersion: v1
kind: Pod
metadata:
  name: centos-image-ghcrio
spec:
  containers:
  - name: pod-case-0
    image: ghcr.io/easybuilders/centos-7.9:latest
    command:
    - /sbin/init