apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: observability
data:
  config.yml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'
    route:
      receiver: "lernmat.mario@gmail.com"
    receivers:
      - name: "lernmat.mario@gmail.com"
    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: alertmanager
  template:
    metadata:
      labels:
        tier: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:main
        args:
        - "--config.file=/etc/alertmanager/config.yml"
        ports:
          - containerPort: 9093
        volumeMounts:
          - name: alertmanager-config
            mountPath: /etc/alertmanager
      volumes:
        - name: alertmanager-config
          configMap:
            name: alertmanager-config
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: observability
spec:
  type: ClusterIP
  selector:
    tier: alertmanager
  ports:
  - name: http
    port: 9093
    targetPort: 9093
    protocol: TCP
      
