apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-redis-server
  namespace: redis
data:
  redis.conf: |
    # Allow connections from any client
    bind 0.0.0.0 ::
    protected-mode no
    port 6379
    tcp-keepalive 300

    # Data Store
    dir /data
    databases 15
    dbfilename dump.rdb
    appendonly no
    save ""

    # Authentication
    user default off
    user tectelUser on >tectelUser123 ~* +@all

    # Logging
    logfile ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis-server
  namespace: redis
  labels:
    tier: redisdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redisdb-server
  namespace: redis
  labels:
    tier: redisdbdb
spec:
  selector:
    matchLabels:
      tier: redisdbdb
  serviceName: redisdb-server
  replicas: 1
  template:
    metadata:
      labels:
        tier: redisdbdb
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: redisdb
        image: redis:8-alpine
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
          name: client
        - containerPort: 16379
          name: gossip
        volumeMounts:
        - name: persistent-storage
          mountPath: /data
        - name: config
          mountPath: /usr/local/etc/redis/redis.conf
          subPath: redis.conf
        env:
        - name: TZ
          value: "UTC"
        resources: {}
      - name: redis-exporter
        image: bitnami/redis_exporter
        args:
        - "--redis.addr=localhost:6379"
        - "--redis.password=tectelUser123"
        - "--redis.user=tectelUser"
        ports:
        - containerPort: 9121
      volumes:
      - name: config
        configMap:
          defaultMode: 0666
          name: configmap-redis-server
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: pvc-redis-server
---
apiVersion: v1
kind: Service
metadata:
  name: svc-redis-server
  namespace: redis
spec:
  type: ClusterIP
  selector:
    tier: redisdbdb
  ports:
  - port: 6379
    targetPort: 6379
    name: client
  - port: 16379
    targetPort: 16379
    name: gossip
  - port: 9121
    targetPort: 9121
    name: metrics
