apiVersion: v1
kind: Secret
metadata:
  name: kubernetesui-headlamp
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: "headlamp"
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: headlamp
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: headlamp
  namespace: kube-system
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubernetesui-headlamp
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: headlamp
  template:
    metadata:
      labels:
        k8s-app: headlamp
    spec:
      serviceAccountName: headlamp
      containers:
      - name: headlamp
        image: ghcr.io/headlamp-k8s/headlamp
        imagePullPolicy: IfNotPresent
        args:
        - -in-cluster
        - -plugins-dir=/headlamp/plugins
        - -log-level=debug
        - -insecure-ssl
        - -metrics-enabled=true
        - -stdout-trace-enabled
        - -in-cluster-context-name=minikube
        env:
        - name: HEADLAMP_CONFIG_TRACING_ENABLED
          value: "true"
        - name: HEADLAMP_CONFIG_METRICS_ENABLED
          value: "true"
        - name: HEADLAMP_CONFIG_SERVICE_NAME
          value: "headlamp"
        - name: HEADLAMP_CONFIG_SERVICE_VERSION
          value: "latest"
        - name: HEADLAMP_CHECK_FOR_UPDATES
          value: "true"
        ports:
        - containerPort: 4466
          name: http
        - containerPort: 9090
          name: metrics
        resources: {}   
---
# kind: Service
# apiVersion: v1
# metadata:
#   name: kubernetesui-headlamp
#   namespace: kube-system
# spec:
#   type: NodePort
#   ports:
#   - port: 80
#     targetPort: 4466
#   selector:
#     k8s-app: headlamp

###################################################################################################################
# To generate a secret
# kubectl create secret generic headlamp-kubeconfig --from-file=config=$HOME/.kube/config -n kube-system --dry-run=client -oyaml
# To obtain the login token
# kubectl -n test-headlamp get secret kubernetesui-headlamp -o jsonpath='{.data.token}' | base64 --decode; echo
###################################################################################################################